services:
  wastream:
    image: dydhzo/wastream:latest
    container_name: wastream
    ports:
      - "7000:7000"
    volumes:
      - ./data:/app/data
    environment:
      - WAWACITY_URL=https://example.com # OBLIGATOIRE
      - PORT=7000
      - DATABASE_TYPE=sqlite
      - DATABASE_PATH=/app/data/wastream.db
    restart: unless-stopped
